apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-client
  template:
    metadata:
      labels:
        app: echo-client
    spec:
      containers:
      - name: echo-client
        image: boanlab/cryptoflex-test-client
        ports:
        - containerPort: 65432
