#!/bin/bash

CONTAINER="istio-proxy"
CONFIG_FILE="/var/lib/istio/data/cryptoflex.conf"

usage() {
    echo "Usage: $0 -n <namespace> <pod> [bssl|ossl]"
    echo "Example: $0 -n test echo-server bssl"
    exit 1
}

# Parse command line arguments
while getopts "n:" opt; do
    case $opt in
        n)
            NAMESPACE="$OPTARG"
            ;;
        \?)
            usage
            ;;
    esac
done

# Shift past the last option
shift $((OPTIND-1))

# Check if all required arguments are provided
if [ -z "$NAMESPACE" ] || [ $# -ne 2 ]; then
    usage
fi

POD="$1"
TYPE="$2"

# Check if argument is valid
case "$TYPE" in
    "bssl"|"ossl")
        kubectl exec -n "$NAMESPACE" "$POD" -c $CONTAINER -- /bin/sh -c "echo '$TYPE' > $CONFIG_FILE"
        ;;
    *)
        echo "Error: Invalid argument. Use either 'bssl' or 'ossl'"
        usage
        ;;
esac