apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/${HUB}
  tag: ${TAG}
  meshConfig:
    accessLogFile: /dev/stdout
    enableTracing: true
    meshMTLS:
      minProtocolVersion: TLSV1_3
      cipherSuites:
      - TLS_CHACHA20_POLY1305_SHA256
  values:
    global:
      imagePullPolicy: Always
      proxy:
        logLevel: trace
        componentLogLevel: "misc:trace,http:debug,config:trace,client:trace,filter:debug"

