apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: docker.io/boanlab
  tag: latest
  meshConfig:
    meshMTLS:
      cipherSuites:
      - TLS_AES_256_GCM_SHA384